extends: MH0386
queue_rules:
  - name: Python Dependency Updates
    allow_queue_branch_edit: true
    max_checks_retries: 3
    queue_conditions:
      - files ~= ^(uv.lock|pyproject.toml)$
      - author = renovate[bot]
      - check-success = Check Dependency Compatibility
      - check-success = Clean Jupyter Notebooks
    merge_conditions:
      - check-success = Check Jupyter Notebooks
merge_protections_settings:
  auto_merge_conditions: true
  reporting_method: check-runs
