[tools]
"aqua:quarto-dev/quarto-cli" = "latest"
"pipx:nb-clean" = "latest"
uv = "latest"

[tasks]
check-deps = { run = "uv lock --check" }
clean-jupyter = { run = "nb-clean clean -o -e ./notebooks/" }
check-jupyter = { run = "nb-clean check -o -e ./notebooks/" }
render = { run = "quarto render" }

[settings]
minimum_release_age = "0d"
